//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v11.4.0+e52e987
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Generic Details Page</summary>
	[PublishedModel("genericDetailsPage")]
	public partial class GenericDetailsPage : PublishedContentModel, IAttachmentsSection, IContentComponentSection, IContentSection, IFAqsSection, IGallery, IMainImageComp, IMainTitle, IRelatedLinks, ISEosettings, ISharingComponent
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		public new const string ModelTypeAlias = "genericDetailsPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<GenericDetailsPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public GenericDetailsPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Brief
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("brief")]
		public virtual string Brief => this.Value<string>(_publishedValueFallback, "brief");

		///<summary>
		/// Category
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("category")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent Category => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "category");

		///<summary>
		/// Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[ImplementPropertyType("date")]
		public virtual global::System.DateTime Date => this.Value<global::System.DateTime>(_publishedValueFallback, "date");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("description")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString Description => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "description");

		///<summary>
		/// Attachment Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("attachmentTitle")]
		public virtual string AttachmentTitle => global::Umbraco.Cms.Web.Common.PublishedModels.AttachmentsSection.GetAttachmentTitle(this, _publishedValueFallback);

		///<summary>
		/// Files
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("files")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel Files => global::Umbraco.Cms.Web.Common.PublishedModels.AttachmentsSection.GetFiles(this, _publishedValueFallback);

		///<summary>
		/// Contetn Component Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contetnComponentTitle")]
		public virtual string ContetnComponentTitle => global::Umbraco.Cms.Web.Common.PublishedModels.ContentComponentSection.GetContetnComponentTitle(this, _publishedValueFallback);

		///<summary>
		/// CTA
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cTA")]
		public virtual global::Umbraco.Cms.Core.Models.Link CTA => global::Umbraco.Cms.Web.Common.PublishedModels.ContentComponentSection.GetCTA(this, _publishedValueFallback);

		///<summary>
		/// Media Item
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mediaItem")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MediaItem => global::Umbraco.Cms.Web.Common.PublishedModels.ContentComponentSection.GetMediaItem(this, _publishedValueFallback);

		///<summary>
		/// content section Items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contentSectionItems")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel ContentSectionItems => global::Umbraco.Cms.Web.Common.PublishedModels.ContentSection.GetContentSectionItems(this, _publishedValueFallback);

		///<summary>
		/// FaqsList
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("faqsList")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel FaqsList => global::Umbraco.Cms.Web.Common.PublishedModels.FAqsSection.GetFaqsList(this, _publishedValueFallback);

		///<summary>
		/// FAQs Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fAQsTitle")]
		public virtual string FAqsTitle => global::Umbraco.Cms.Web.Common.PublishedModels.FAqsSection.GetFAqsTitle(this, _publishedValueFallback);

		///<summary>
		/// Gallery Section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("gallerySection")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel GallerySection => global::Umbraco.Cms.Web.Common.PublishedModels.Gallery.GetGallerySection(this, _publishedValueFallback);

		///<summary>
		/// Gallery Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("galleryTitle")]
		public virtual string GalleryTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Gallery.GetGalleryTitle(this, _publishedValueFallback);

		///<summary>
		/// Cover Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("coverImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CoverImage => global::Umbraco.Cms.Web.Common.PublishedModels.MainImageComp.GetCoverImage(this, _publishedValueFallback);

		///<summary>
		/// Title: Maximum allowed characters 100
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => global::Umbraco.Cms.Web.Common.PublishedModels.MainTitle.GetTitle(this, _publishedValueFallback);

		///<summary>
		/// Related link Items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("relatedLinkItems")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> RelatedLinkItems => global::Umbraco.Cms.Web.Common.PublishedModels.RelatedLinks.GetRelatedLinkItems(this, _publishedValueFallback);

		///<summary>
		/// Related link Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("relatedLinkTitle")]
		public virtual string RelatedLinkTitle => global::Umbraco.Cms.Web.Common.PublishedModels.RelatedLinks.GetRelatedLinkTitle(this, _publishedValueFallback);

		///<summary>
		/// SEO Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sEODescription")]
		public virtual string SEodescription => global::Umbraco.Cms.Web.Common.PublishedModels.SEosettings.GetSEodescription(this, _publishedValueFallback);

		///<summary>
		/// SEO Keywords
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sEOKeywords")]
		public virtual string SEokeywords => global::Umbraco.Cms.Web.Common.PublishedModels.SEosettings.GetSEokeywords(this, _publishedValueFallback);

		///<summary>
		/// SEO Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sEOTitle")]
		public virtual string SEotitle => global::Umbraco.Cms.Web.Common.PublishedModels.SEosettings.GetSEotitle(this, _publishedValueFallback);

		///<summary>
		/// CopyLink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[ImplementPropertyType("copyLink")]
		public virtual long CopyLink => global::Umbraco.Cms.Web.Common.PublishedModels.SharingComponent.GetCopyLink(this, _publishedValueFallback);

		///<summary>
		/// Facebook
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[ImplementPropertyType("facebook")]
		public virtual long Facebook => global::Umbraco.Cms.Web.Common.PublishedModels.SharingComponent.GetFacebook(this, _publishedValueFallback);

		///<summary>
		/// Twitter
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[ImplementPropertyType("twitter")]
		public virtual long Twitter => global::Umbraco.Cms.Web.Common.PublishedModels.SharingComponent.GetTwitter(this, _publishedValueFallback);

		///<summary>
		/// WhatsApp
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.0+e52e987")]
		[ImplementPropertyType("whatsApp")]
		public virtual long WhatsApp => global::Umbraco.Cms.Web.Common.PublishedModels.SharingComponent.GetWhatsApp(this, _publishedValueFallback);
	}
}
